### ISSUE TITLE
filtername incorrect

### ISSUE THREAD

**Issue by danmarsden** [adpe/moodle-filter_fontawesome#2]
Couple of things wrong with the filtername:

$string['filtername'] = 'FontAwesome Icon Filter.';

Moodle uses sentence case so it should probably be:
$string['filtername'] = 'FontAwesome icon filter.';

Also - the plugin name doesn't usually include the plugin "type" - in your case "filter"
so it might be better to be:
$string['filtername'] = 'FontAwesome';

or maybe even something like:
$string['filtername'] = 'FontAwesome icons.';

Probably been there since Julian created it and no-one had noticed :-)

**Comment by adpe** [comment]
Hi @danmarsden 

I changed it right now. Thank you!
