### ISSUE TITLE
Missing privacy API

### ISSUE THREAD

**Issue by danmarsden** [adpe/moodle-filter_fontawesome#3]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. It doesn't look like your plugin stores user data so you may be able to implement the null provider.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

please note this is not a blocker for re-approval in the plugins db - but I do see a pull request has been made for this which is nice - hopefully you can merge it.

**Comment by adpe** [comment]
Hi @danmarsden 

Thanks for your contribution. Just bumped the version and I'll upload it to the Moodle plugins repo.
